# Generated by Django 4.2.2 on 2023-06-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_iec_60870_5_104_master_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusslavertu',
            name='Registers_type',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Data_bits',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Speed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modbusikmastertcp',
            name='LogLevel',
            field=models.CharField(max_length=255),
        ),
    ]
