# Generated by Django 4.2.2 on 2023-06-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_modbusslavertu_registers_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='IOA',
            field=models.IntegerField(null=True),
        ),
    ]
