# Generated by Django 4.2.2 on 2023-06-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_iec_60870_5_104_slave_ioa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='Range',
            field=models.IntegerField(null=True),
        ),
    ]
