# Generated by Django 4.2.2 on 2023-06-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_iec_60870_5_104_slave_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='iec_60870_5_104_master',
            name='Sector',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iec_60870_5_104_slave',
            name='Sector',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modbusikmasterrtu',
            name='Sector',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modbusikmastertcp',
            name='Sector',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modbusslavertu',
            name='Sector',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modbusslavetcp',
            name='Sector',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
    ]
