# Generated by Django 4.2 on 2023-07-14 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_iec_60870_5_104_master_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iec_60870_5_104_master',
            name='Command',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_master',
            name='Data',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_master',
            name='Endpoints',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_master',
            name='Files',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_master',
            name='Interrogation_periods',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='ASDU',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='Cause_of_transmission',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='Count',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='Groups',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='IOA',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='Range',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='iec_60870_5_104_slave',
            name='Type_send',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Bytes_Order',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Composition',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Control',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Count',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Data_Type',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Filter',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Period',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Registers_Type',
        ),
        migrations.RemoveField(
            model_name='modbusikmasterrtu',
            name='Start',
        ),
        migrations.RemoveField(
            model_name='modbusikmastertcp',
            name='Endpoints',
        ),
        migrations.RemoveField(
            model_name='modbusikmastertcp',
            name='Read_registers',
        ),
        migrations.RemoveField(
            model_name='modbusikmastertcp',
            name='Write_registers',
        ),
        migrations.RemoveField(
            model_name='modbusslavertu',
            name='Count',
        ),
        migrations.RemoveField(
            model_name='modbusslavertu',
            name='Registers',
        ),
        migrations.RemoveField(
            model_name='modbusslavertu',
            name='Registers_type',
        ),
        migrations.RemoveField(
            model_name='modbusslavetcp',
            name='Registers',
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_master',
            name='Autorun',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_master',
            name='Filter',
            field=models.CharField(choices=[('None', 'None'), ('Partial', 'Partial'), ('Full', 'Full')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_master',
            name='LogLevel',
            field=models.CharField(choices=[('Trace', 'Trace'), ('Debug', 'Debug'), ('Info', 'Info'), ('Warn', 'Warn'), ('Error', 'Error'), ('Off', 'Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_master',
            name='Port',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_master',
            name='Sector',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_master',
            name='SplitIntoParts',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_master',
            name='TimeSync',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_master',
            name='TimeSyncFormat',
            field=models.CharField(choices=[('UTC', 'UTC'), ('Localtime', 'Localtime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='Autorun',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='Command',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='Data',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='Files',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='Filter',
            field=models.CharField(choices=[('None', 'None'), ('Partial', 'Partial'), ('Full', 'Full')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='LogLevel',
            field=models.CharField(choices=[('Trace', 'Trace'), ('Debug', 'Debug'), ('Info', 'Info'), ('Warn', 'Warn'), ('Error', 'Error'), ('Off', 'Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='Port',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='iec_60870_5_104_slave',
            name='Sector',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Autorun',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Data_bits',
            field=models.CharField(choices=[('Seven', '7'), ('Eight', '8')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='LogLevel',
            field=models.CharField(choices=[('Trace', 'Trace'), ('Debug', 'Debug'), ('Info', 'Info'), ('Warn', 'Warn'), ('Error', 'Error'), ('Off', 'Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Parity',
            field=models.CharField(choices=[('None', 'None'), ('Odd', 'Odd'), ('Even', 'Even'), ('Mark', 'Mark'), ('Space', 'Space')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Port',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Read_registers',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Sector',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Speed',
            field=models.CharField(choices=[('s1200', '1200'), ('s2400', '2400'), ('s4800', '4800'), ('s9600', '9600'), ('s19200', '19200'), ('s38400', '38400'), ('s57600', '57600'), ('s115200', '115200')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Stop_bits',
            field=models.CharField(choices=[('One', 'One'), ('One5', 'One5'), ('Two', 'Two')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmasterrtu',
            name='Write_registers',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modbusikmastertcp',
            name='Autorun',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmastertcp',
            name='LogLevel',
            field=models.CharField(choices=[('Trace', 'Trace'), ('Debug', 'Debug'), ('Info', 'Info'), ('Warn', 'Warn'), ('Error', 'Error'), ('Off', 'Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmastertcp',
            name='Pause',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmastertcp',
            name='Port',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmastertcp',
            name='Read_timeout',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusikmastertcp',
            name='Sector',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modbusikmastertcp',
            name='Station_Address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavertu',
            name='Autorun',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavertu',
            name='Data_bits',
            field=models.CharField(choices=[('Seven', '7'), ('Eight', '8')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavertu',
            name='Parity',
            field=models.CharField(choices=[('None', 'None'), ('Odd', 'Odd'), ('Even', 'Even'), ('Mark', 'Mark'), ('Space', 'Space')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavertu',
            name='Port',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavertu',
            name='Sector',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modbusslavertu',
            name='Speed',
            field=models.CharField(choices=[('s1200', '1200'), ('s2400', '2400'), ('s4800', '4800'), ('s9600', '9600'), ('s19200', '19200'), ('s38400', '38400'), ('s57600', '57600'), ('s115200', '115200')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavertu',
            name='Stop_bits',
            field=models.CharField(choices=[('One', 'One'), ('One5', 'One5'), ('Two', 'Two')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavertu',
            name='Write_messages_in_log',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavetcp',
            name='Autorun',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavetcp',
            name='Port',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusslavetcp',
            name='Sector',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ModbusSlaveTCP_dyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registers', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('modbus_slave_TCP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.modbusslavetcp')),
            ],
        ),
        migrations.CreateModel(
            name='ModbusSlaveRTU_dyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.CharField(blank=True, max_length=255)),
                ('Registers', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Registers_type', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('modbus_slave_rtu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.modbusslavertu')),
            ],
        ),
        migrations.CreateModel(
            name='ModbusikMasterTCP_dyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Read_registers', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Write_registers', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Endpoints', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('modbusik_master_TCP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.modbusikmastertcp')),
            ],
        ),
        migrations.CreateModel(
            name='ModbusikMasterRTU_dyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registers_Type', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Start', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Data_Type', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Count', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Bytes_Order', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Period', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Filter', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Name', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Composition', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Control', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('modbusik_master_rtu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.modbusikmasterrtu')),
            ],
        ),
        migrations.CreateModel(
            name='IEC_60870_5_104_Slave_dyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255)),
                ('ASDU', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Address', models.IntegerField(blank=True, null=True)),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, max_length=255)),
                ('Groups', models.CharField(blank=True, max_length=255)),
                ('Cause_of_transmission', models.CharField(blank=True, max_length=255)),
                ('IOA', models.IntegerField(blank=True, null=True)),
                ('Range', models.IntegerField(blank=True, null=True)),
                ('Type_send', models.CharField(blank=True, max_length=255)),
                ('iec_60870_5_104_slave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.iec_60870_5_104_slave')),
            ],
        ),
        migrations.CreateModel(
            name='IEC_60870_5_104_Master_dyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Command', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Files', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Endpoints', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('Interrogation_periods', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('iec_60870_5_104_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.iec_60870_5_104_master')),
            ],
        ),
    ]
