# Generated by Django 4.2 on 2023-07-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_iec_60870_5_104_master_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusslavertu_dyn',
            name='Address',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
    ]
