from django.db import models



class ModbusSlaveTCP(models.Model):
    IP = models.CharField(max_length=15)
    Port = models.CharField(max_length=255)

    Clients_Count = models.IntegerField()
    Device_Address = models.IntegerField()
    Autorun = models.BooleanField()

class ModbusikMasterTCP(models.Model):
    Ip = models.CharField(max_length=15)
    Port = models.CharField(max_length=255)
    Read_timeout = models.IntegerField()
    Pause = models.IntegerField()
    Station_Address = models.IntegerField()
    Reconnect = models.IntegerField()
    NumberOfReconnections = models.IntegerField()
    Allowed_errors = models.IntegerField()
    LogLevel = models.IntegerField()
    Autorun = models.BooleanField()

class ModbusSlaveRTU(models.Model):
    Port = models.CharField(max_length=255)
    Address = models.IntegerField()
    Speed = models.IntegerField()
    Parity = models.CharField(max_length=15)
    Stop_bits = models.CharField(max_length=255)
    Data_bits = models.IntegerField()
    Count = models.IntegerField()
    Number_of_reconnections = models.IntegerField()
    Write_messages_in_log = models.BooleanField()
    Autorun = models.BooleanField()

class ModbusikMasterRTU(models.Model):
    Port = models.CharField(max_length=255)
    Speed = models.IntegerField()
    Parity = models.CharField(max_length=15)
    Stop_bits = models.CharField(max_length=255)
    Data_bits = models.IntegerField()
    Number_of_retries = models.IntegerField()
    Read_timeout = models.IntegerField()
    Pause = models.IntegerField()
    Station_Address = models.IntegerField()
    Reconnect = models.IntegerField()
    Allowed_errors = models.IntegerField()
    LogLevel = models.CharField(max_length=255)
    Autorun = models.BooleanField()

class IEC_60870_5_104_Slave(models.Model):
    Port = models.CharField(max_length=255)
    Name = models.CharField(max_length=255)
    ASDU = models.IntegerField()
    Address = models.IntegerField()
    Count = models.IntegerField()
    Type = models.CharField(max_length=255)
    Groups = models.CharField(max_length=255)
    Cause_of_transmission = models.CharField(max_length=255)
    IOA = models.IntegerField()
    Range = models.IntegerField()
    Type_send = models.CharField(max_length=255)
    AnswerTimeout = models.IntegerField()
    InfoTimeout = models.IntegerField()
    Downtime = models.IntegerField()
    W = models.IntegerField()
    K = models.IntegerField()
    MaxConnectionCount = models.IntegerField()
    QueueSize = models.IntegerField()
    Filter = models.CharField(max_length=255)
    LogLevel = models.CharField(max_length=255)
    Autorun = models.BooleanField()

class IEC_60870_5_104_Master(models.Model):
    IP = models.CharField(max_length=15)
    Port = models.CharField(max_length=255)
    Reconnect = models.IntegerField()
    T1 = models.IntegerField()
    T2 = models.IntegerField()
    T3 = models.IntegerField()
    W = models.IntegerField()
    K = models.IntegerField()
    TimeSync = models.BooleanField()
    TimeSyncFormat = models.CharField(max_length=255)
    TimeShift = models.IntegerField()
    Filter = models.CharField(max_length=255)
    NumberOfReconnections = models.IntegerField()
    SplitIntoParts = models.BooleanField()
    LogLevel = models.CharField(max_length=255)
    Autorun = models.BooleanField()
